const user = db.users.findOne({email: "hdregistros@sigcr.com.br"});
if (!user) { print("ERRO: usuario nao encontrado - faca login no sistema primeiro"); quit(1); }
let company = db.companies.findOne({user_id: user.user_id, name: "HD Registros"});
if (!company) {
  company = {
    company_id: "company_hdregistros",
    user_id: user.user_id,
    name: "HD Registros",
    nome_fantasia: "HD Registros",
    cnpj: "PENDENTE",
    endereco: "",
    email_comercial: "contato@hdregistros.com.br",
    whatsapp: "",
    gestor_contrato: "Pedro",
    detrans_atuacao: ["AC","AP","BA","CE","DF","ES","MG","MS","MT","PB","PE","PI","PR","RJ","RN","RO","RR","RS","SC","SP","TO","MA"],
    status: "approved",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  };
  db.companies.insertOne(company);
  print("Empresa HD Registros criada");
} else {
  print("Empresa HD Registros ja existia");
}
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "AC"}, {$set: {credenciamento_id: "cred_ac", company_id: company.company_id, estado_sigla: "AC", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/AC/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "AP"}, {$set: {credenciamento_id: "cred_ap", company_id: company.company_id, estado_sigla: "AP", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/AP/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "BA"}, {$set: {credenciamento_id: "cred_ba", company_id: company.company_id, estado_sigla: "BA", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/BA/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "CE"}, {$set: {credenciamento_id: "cred_ce", company_id: company.company_id, estado_sigla: "CE", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/CE/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "DF"}, {$set: {credenciamento_id: "cred_df", company_id: company.company_id, estado_sigla: "DF", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/DF/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "ES"}, {$set: {credenciamento_id: "cred_es", company_id: company.company_id, estado_sigla: "ES", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/ES/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "MG"}, {$set: {credenciamento_id: "cred_mg", company_id: company.company_id, estado_sigla: "MG", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/MG/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "MS"}, {$set: {credenciamento_id: "cred_ms", company_id: company.company_id, estado_sigla: "MS", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/MS/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "MT"}, {$set: {credenciamento_id: "cred_mt", company_id: company.company_id, estado_sigla: "MT", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/MT/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "PB"}, {$set: {credenciamento_id: "cred_pb", company_id: company.company_id, estado_sigla: "PB", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/PB/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "PE"}, {$set: {credenciamento_id: "cred_pe", company_id: company.company_id, estado_sigla: "PE", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/PE/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "PI"}, {$set: {credenciamento_id: "cred_pi", company_id: company.company_id, estado_sigla: "PI", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/PI/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "PR"}, {$set: {credenciamento_id: "cred_pr", company_id: company.company_id, estado_sigla: "PR", extrato_contrato: "Documento oficial de credenciamento", status: "sem_efeito", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/PR/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "RJ"}, {$set: {credenciamento_id: "cred_rj", company_id: company.company_id, estado_sigla: "RJ", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/RJ/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "RN"}, {$set: {credenciamento_id: "cred_rn", company_id: company.company_id, estado_sigla: "RN", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/RN/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "RO"}, {$set: {credenciamento_id: "cred_ro", company_id: company.company_id, estado_sigla: "RO", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/RO/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "RR"}, {$set: {credenciamento_id: "cred_rr", company_id: company.company_id, estado_sigla: "RR", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/RR/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "RS"}, {$set: {credenciamento_id: "cred_rs", company_id: company.company_id, estado_sigla: "RS", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/RS/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "SC"}, {$set: {credenciamento_id: "cred_sc", company_id: company.company_id, estado_sigla: "SC", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/SC/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "SP"}, {$set: {credenciamento_id: "cred_sp", company_id: company.company_id, estado_sigla: "SP", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/SP/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "TO"}, {$set: {credenciamento_id: "cred_to", company_id: company.company_id, estado_sigla: "TO", extrato_contrato: "Documento oficial de credenciamento", status: "ativo", termo_credenciamento_path: "/opt/biosintese/sigcr/uploads/credenciamentos/TO/documento-oficial.pdf", created_at: new Date().toISOString()}}, {upsert: true});
db.credenciamentos.updateOne({company_id: company.company_id, estado_sigla: "MA"}, {$set: {credenciamento_id: "cred_ma", company_id: company.company_id, estado_sigla: "MA", extrato_contrato: "Credenciamento em andamento", status: "pendente", termo_credenciamento_path: null, created_at: new Date().toISOString()}}, {upsert: true});
print("Estados populados: " + db.credenciamentos.countDocuments({company_id: company.company_id}));
